jQuery(document).ready(function() {var params = {
rssmikle_url: "http://yosemiteblog.com/feed/|
	http://www.nps.gov/grca/planyourvisit/upload/grca-backcountry.xml|
	http://w1.weather.gov/xml/current_obs/KBCE.rss|
	http://www.nature.nps.gov/assets/rss/NRSS.xml",
	rssmikle_frame_width: "300",
	rssmikle_frame_height: "400",
	rssmikle_target: "_blank",
	rssmikle_font: "Arial, 
	Helvetica, sans-serif",
	rssmikle_font_size: "10",
	rssmikle_border: "off",
	responsive: "on",
	rssmikle_css_url: "",
	text_align: "left",
	text_align2: "left",
	corner: "off",
	scrollbar: "on",
	autoscroll: "on",
	scrolldirection: "up",
	scrollstep: "3",
	mcspeed: "20",
	sort: "New",
	rssmikle_title: "on",
	rssmikle_title_sentence: "Travel Info Live Feeds",
	rssmikle_title_link: "",
	rssmikle_title_bgcolor: "#B92EFF",
	rssmikle_title_color: "#91FFA4",
	rssmikle_title_bgimage: "",
	rssmikle_item_bgcolor: "#F3DEFF",
	rssmikle_item_bgimage: "",
	rssmikle_item_title_length: "55",
	rssmikle_item_title_color: "#7A14FF",
	rssmikle_item_border_bottom: "on",
	rssmikle_item_description: "on",
	item_link: "on",
	rssmikle_item_description_length: "150",
	rssmikle_item_description_color: "#0A0A0A",
	rssmikle_item_date: "gl2",
	rssmikle_timezone: "Australia/Sydney",
	datetime_format: "%e.%m.%Y %l:%M:%S %p",
	rssmikle_item_description_tag: "on_html",
	rssmikle_item_description_image_scaling: "on",
	article_num: "25",
	rssmikle_item_podcast: "off",
	keyword_inc: "",keyword_exc: ""}}); 
	
	feedwind_show_widget_iframe(params); 
				