/*
 * FILo <> Facebook Image Loader jQuery Plugin v1.2.2
 * http://www.berlinpix.com/filo
 *
 * Copyright 2014, BerlinPix.com
 * licensed under the LGPL license.
 *
 * last update: 2014-03-05
 */
(function(c){function t(a,b,c,d){if("function"==typeof d.before){var e=jQuery.Event("FILo Before Event");d.before(e)}e=a.filo.root_path;e=void 0==d.filo_loaderGraphic?e+a.filo.filo_loaderGraphicDefault:d.filo_loaderGraphic;if(null==a(".filo_loader")||0==a(".filo_loader").length){var g=new Image;g.onload=function(){a(g).css("marginTop",-1*(this.height/2));a(g).css("marginLeft",-1*(this.width/2));a("#"+String(b)).append(g)};g.setAttribute("class","filo_loader");g.src=e}var i=[];a.each(a("#"+String(b)).find(".excluded"),
function(b,c){i.push(a(c).attr("id"))});var f=[];a.each(a("#"+b).find(".album"),function(b,c){f.push(a(c).attr("id"))});if(void 0!=d.albums&&0<d.albums.length)for(e=0;e<d.albums.length;e++)f.push(decodeURI(d.albums[e]));if(void 0!=d.excluded&&0<d.excluded.length)for(e=0;e<d.excluded.length;e++)i.push(decodeURI(d.excluded[e]));var e="https://graph.facebook.com/fql?q=",j="",j=isNaN(c)?JSON.stringify({page_id:"SELECT page_id FROM page WHERE username = '"+c+"'",albums:"SELECT aid, name FROM album WHERE owner IN (SELECT page_id FROM #page_id)"}):
JSON.stringify({albums:"SELECT aid, name FROM album WHERE owner = "+c}),e=e+encodeURIComponent(j);a.browser.msie?a.ajax({url:e,dataType:"jsonp"}).success(function(h){h=h.data;w(a,b,c,1<h.length?h[1].fql_result_set:h[0].fql_result_set,f,i,d)}):a.getJSON(e,function(h){h=h.data;h=1<h.length?h[1].fql_result_set:h[0].fql_result_set;0>=h.length&&(a(".filo_loader").remove(),alert("There are no albums, please check your Facebook-ID"));w(a,b,c,h,f,i,d)}).error(function(){a(".filo_loader").remove();alert("Error while loading, please check your Facebook-ID or write me: info@berlinpix.com")})}
function w(a,b,c,d,e,g,i){a.filo.toLoad[b]=0;a.filo.isLoaded[b]=0;for(album in d)d[album].name=d[album].name.replace(/[\/]/g,":");var f="";0<e.length?a.each(d,function(d,h){if(x(h.name,e)){a.filo.toLoad[b]+=1;var g=a.filo.maxCountDefault;void 0!=a("#"+b+" #"+h.name).attr("maxCount")?g=parseInt(a("#"+b+" #"+h.name).attr("maxCount")):void 0!=a("#"+b+" #"+h.name.toLowerCase()).attr("maxCount")?g=parseInt(a("#"+b+" #"+h.name.toLowerCase()).attr("maxCount")):void 0!=i&&void 0!=i.maxCount&&(g=i.maxCount);
f="all"==g?JSON.stringify({photos:"SELECT src, src_big, src_big_width, images FROM photo WHERE aid = '"+h.aid+"' LIMIT 1000"}):JSON.stringify({photos:"SELECT src, src_big, src_big_width, images FROM photo WHERE aid = '"+h.aid+"' LIMIT "+g});var k="https://graph.facebook.com/fql?q="+encodeURIComponent(f);a("#"+b+" #"+h.name).remove();a("#"+b+" #"+h.name.toLowerCase()).remove();var l=a('<div class="album" id="'+h.name+'"></div>').append('<div class="title">'+h.name.replace(/[:]/g,"/")+'</div><div class="thumbs"></div>');
a(l).hide();a("#"+b).append(l);a.browser.msie?a.ajax({url:k,dataType:"jsonp"}).success(function(d){r(1,a,c,b,d.data[0].fql_result_set,l,g,i)}):a.getJSON(k,function(d){r(1,a,c,b,d.data[0].fql_result_set,l,g,i)})}}):a.each(d,function(d,h){if(!x(h.name,g)){a.filo.toLoad[b]+=1;var e=a.filo.maxCountDefault;void 0!=i&&void 0!=i.maxCount?e=i.maxCount:void 0!=a("#"+h.name).attr("maxCount")&&(e=parseInt(a("#"+h.name).attr("maxCount")));f="all"==e?JSON.stringify({photos:"SELECT src, src_big, src_big_width, images FROM photo WHERE aid = '"+
h.aid+"'"}):JSON.stringify({photos:"SELECT src, src_big, src_big_width, images FROM photo WHERE aid = '"+h.aid+"' LIMIT "+e});var k="https://graph.facebook.com/fql?q="+encodeURIComponent(f),l=a('<div class="album" id="'+h.name+'"></div>').append('<div class="title">'+h.name.replace(/[:]/g,"/")+'</div><div class="thumbs"></div>').hide();a("#"+b).append(l);a.browser.msie?a.ajax({url:k,dataType:"jsonp"}).success(function(d){r(1,a,c,b,d.data[0].fql_result_set,l,e,i)}):a.getJSON(k,function(d){r(1,a,c,
b,d.data[0].fql_result_set,l,e,i)})}})}function r(a,b,c,d,e,g,i,f){var j=1==a?1:26*(a-1),h=[],a=e,m=b.filo.root_path;if(void 0!=f.order&&"reverse"==f.order)a.reverse();else if(void 0!=f.order&&"random"==f.order){for(var k=[],l=[];k.length<i&&k.length<a.length;){var u=Math.floor(Math.random()*a.length);void 0==l[u]&&(k.push(a[u]),l[u]=!0)}a=k}var n=screen.width,r=screen.height,t=n>r;b.each(a,function(a,d){for(var l=d.images[0].source,k=d.images.length-1;0<k;k--)t?n<parseInt(d.images[k].width)&&(l=
d.images[k].source,k=0):r<parseInt(d.images[k].height)&&(l=d.images[k].source,k=0);h[j-1]=l;var k=1==j?" first":"",u=j==i?" last":"",q=new Image;q.setAttribute("class","picture filo_picture");q.setAttribute("id",j-1);var s=0;q.onerror=function(){2>s?(console.log("load picture again: "+d.src),q.src=d.src,s++):(q.onerror=null,q.src=b.filo.root_path+b.filo.defaultImage)};q.src=d.src;l=b('<div class="thumb thumb_'+j+k+u+'"><div class="inner"><a href="'+l+'"></a></div></div>');b(l).find("a").append(q);
b(g).find(".thumbs").append(l);b(g).find(".filo_picture").unbind("click");b(g).find(".filo_picture").click(function(a){a.preventDefault();if(void 0!=f.href)return void 0!=f.method&&"post"==f.method.toLowerCase()?(a=!0==f.newWindow?'target="_blank"':"",b("body").append('<form id="filo_forward" '+a+' method="POST" action="'+f.href+'"><input name="profile" value="'+c+'" /><input name="album" value="'+b(g).attr("id")+'" /></form>'),b("#filo_forward").trigger("submit").remove()):f.newWindow?window.open(f.href+
"?profile="+c+"&album="+b(g).attr("id")):document.location=f.href+"?profile="+c+"&album="+b(g).attr("id"),!1;if(1>b(".filo_overlay").length){b.filo.closeButton=m+b.filo.closeButtons.black;void 0!=f.closeButton&&(b.filo.closeButton=void 0!=b.filo.closeButtons[f.closeButton]?m+b.filo.closeButtons[f.closeButton]:f.closeButton);var d=900;b.each(b("body *"),function(a,c){"auto"!=b(c).css("zIndex")&&(d=Math.max(d,parseInt(b(c).css("zIndex"))))});var a=void 0!=f.overlay?"background: "+f.overlay+"; ":"background: "+
b.filo.overlayDefault+";",e=void 0!=f.overlayOpacity?" opacity: "+f.overlayOpacity+";":" opacity: "+b.filo.overlayOpacityDefault+";";b("body").append('<div class="filo_overlay" style="z-index:'+(d+1)+';" ><div class="filo_overlay_background" style="'+a+e+'"></div><div class="filo_overlay_container"><div class="filo_overlay_container_left"></div><div class="filo_overlay_container_right"></div><div class="picture_counter"></div></div></div>');var i=new Image;i.onload=function(){b(".filo_overlay_container").append(i);
var a=0<b(".filo_overlay_container").css("border-width")?b(".filo_overlay_container").css("border-width"):17;b(this).css("right",-1*(this.width/2+a));b(this).css("top",-1*(this.height/2+a));i.setAttribute("class","filo_overlay_container_close");b(".filo_overlay_container_close").click(function(){b(".filo_overlay").remove()})};i.src=b.filo.closeButton;v(b,b(this).attr("id"),h,b(g).attr("id"),f);b(".filo_overlay_background").click(function(a){"filo_overlay_background"==b(a.target).attr("class")&&b(".filo_overlay").remove()});
b(".filo_overlay_container_left").click(function(){var a=parseInt(b(".filo_full_picture").attr("id"));0<a&&v(b,a-1,h,b(g).attr("id"),f)});b(".filo_overlay_container_right").click(function(){var a=parseInt(b(".filo_full_picture").attr("id"));a<h.length-1&&v(b,a+1,h,b(g).attr("id"),f)});b(".filo_overlay_container_left").mouseenter(function(){b(this).css("backgroundColor","none").css("background-image","url('"+m+"/img/left_white.png')").css("background-repeat","no-repeat").css("background-position",
"left center")}).mouseout(function(){b(this).css("background-image","")});b(".filo_overlay_container_right").mouseenter(function(){b(this).css("backgroundColor","none").css("background-image","url('"+m+"/img/right_white.png')").css("background-repeat","no-repeat").css("background-position","right center")}).mouseout(function(){b(this).css("background-image","")})}});void 0!=f.href&&(b(g).find(".title").unbind("click"),b(g).find(".title").css("cursor","pointer"),b(g).find(".title").click(function(){b(g).find(".filo_picture").first().trigger("click")}));
if(j>=i)return b(g).append('<div class="clear"></div>'),!1;j++;j==e.length&&b(g).append('<div class="clear"></div>')});b.filo.isLoaded[d]+=1;b(g).fadeIn("slow");b.filo.isLoaded[d]==b.filo.toLoad[d]&&(b("#"+d+" .album").last().attr("class",b("#"+d+" .album").last().attr("class")+" last"),b("#"+d).append('<div class="clear"></div>'),b("#"+d+" .add").remove(),b("#"+d+" .excluded").remove(),b("#"+d+" .filo_loader").remove(),"function"==typeof f.load&&(d=jQuery.Event("FILo Load Event"),f.load(d)))}function v(a,
b,c,d,e){a(".filo_overlay_container_left").show();a(".filo_overlay_container_right").show();0==b&&a(".filo_overlay_container_left").hide();b==c.length-1&&a(".filo_overlay_container_right").hide();var g=parseInt(a(".filo_overlay_container").css("border-top-width").split("px")[0]),i=parseInt(a(".picture_counter").height()),f=(e.maxWidth?e.maxWidth:a.filo.maxWidth)/100,e=(e.maxHeight?e.maxHeight:a.filo.maxHeight)/100,j=a(window).width()*f-g,h=a(window).height()*e-(g+i),m=new Image;m.onload=function(){var e=
this.width,f=this.height,g,n;e>f?(g=e>j?j:e,n=g*f/e,n>h&&(n=f>h?h:f,g=n*e/f)):(n=f>h?h:f,g=n*e/f,g>j&&(g=e>j?j:e,n=g*f/e));0<a(".filo_overlay_container .filo_full_picture").length?a(".filo_overlay_container .filo_full_picture").fadeOut(300,function(){a(m).css("display","none");m.width=g;m.height=n;a(".filo_overlay_container").width(g).height(n).css("margin-left",-1*(g/2)).css("margin-top",-1*(n/2)-i).prepend(m).find(m).fadeIn(300);a(this).remove();a(".filo_overlay_container_close").show();a(".filo_overlay_container .picture_counter").html("<span>Album: "+
d+" | Pic: "+(parseInt(b)+1)+" of "+c.length+"</span>")}):(a(m).width(g).height(n),a(".filo_overlay_container").width(g).height(n).css("margin-left",-1*(g/2)).css("margin-top",-1*(n/2)-i).prepend(m).fadeIn(300),a(".filo_overlay_container_close").show(),a(".filo_overlay_container .picture_counter").html("<span>Album: "+d+" | Pic: "+(parseInt(b)+1)+" of "+c.length+"</span>"));e=a(".filo_overlay_container .picture_counter span").width();a(".filo_overlay_container .picture_counter span").css("paddingLeft").split("px");
f=a(".filo_overlay_container .picture_counter span").css("paddingRight").split("px")[0];a(".filo_overlay_container .picture_counter").width(e+parseInt(f)+parseInt(f)).css("position","absolute").css("left","50%").css("marginLeft","-"+(e+parseInt(f)+parseInt(f))/2+"px")};m.setAttribute("class","filo_full_picture");m.setAttribute("id",b);m.src=c[b]}function s(a,b){if(0<a(".filo_overlay").length&&!a.filo.resize){a(".filo_full_picture").css("width","").css("height","");resize=!0;var c=(b.maxWidth?b.maxWidth:
a.filo.maxWidth)/100,d=(b.maxHeight?b.maxHeight:a.filo.maxHeight)/100,e=parseInt(a(".filo_overlay_container").css("border-top-width").split("px")[0]),g=parseInt(a(".picture_counter").height()),c=a(window).width()*c-e,d=a(window).height()*d-(e+g),e=parseInt(a(".filo_full_picture").width()),i=parseInt(a(".filo_full_picture").height()),f,j;e>i?(f=e>c?c:e,j=f*i/e,j>d&&(j=i>d?d:i,f=j*e/i)):(j=i>d?d:i,f=j*e/i,f>c&&(f=e>c?c:e,j=f*i/e));a(".filo_overlay_container img.filo_full_picture").width(f);a(".filo_overlay_container").width(f).height(j).css("margin-left",
-1*(f/2)).css("margin-top",-1*(j/2)-g);resize=!1}}function x(a,b){for(var c=0;c<b.length;c++)if(a.toLowerCase()==b[c].toLowerCase())return!0;return!1}c.fn.filo=function(a){if(c(this).length){void 0==a&&(a={container:this});-1==(void 0!=c(this).attr("class")&&c(this).attr("class").indexOf("template"))&&void 0!=a.template?c(this).addClass("template_"+a.template+" filo"):c(this).addClass("filo");var b=c(this).attr("id"),p=b+"_"+Date.now(),p=p.replace(/\./g,"");c(this).attr("id",p);t(c,p,b,a);c(window).unbind("resize");
c(window).resize(function(){s(c,a)})}else console.log("filo container is undefined, please check the ID or class name")};c.filo=function(a,b){void 0==b?b={container:"body"}:void 0==b.container&&(b.container="body");var p=a+"_"+Date.now(),p=p.replace(/\./g,""),d=void 0!=b.template?"template_"+b.template:"";c(b.container).append('<div class="filo '+d+'" id="'+p+'"></div>');t(c,p,a,b);c(window).unbind("resize");c(window).resize(function(){s(c,b)})};jQuery.filo.getUrlParams=function(){for(var a=[],b,
c=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),d=0;d<c.length;d++)b=c[d].split("="),a.push(b[0]),a[b[0]]=b[1];return a};c(document).ready(function(){c.filo.toLoad=[];c.filo.isLoaded=[];c.filo.maxCountDefault=3;c.filo.overlayDefault="rgb(177,177,177)";c.filo.overlayOpacityDefault=0.5;c.filo.filo_loaderGraphicDefault="/img/bpx_loader.gif";c.filo.photos_array=null;c.filo.resize=!1;c.filo.closeButtons={black:"/img/close_black.png",white:"/img/close_white.png"};c.filo.defaultImage=
"/img/default.png";c.filo.order=["normal","reverse","random"];c.filo.method="post";c.filo.newWindow=!1;var a=c.filo,b;a:{try{throw Error();}catch(p){var d="";void 0!=p.fileName?d=p.fileName.split("/"):(b=document.getElementsByTagName("script"),c.each(b,function(a,b){0<=b.src.indexOf("filo.js")&&(d=b.src.split("/"))}));if(""==d){b="filo/";break a}}b="";for(var e=0;e<d.length-1;e++)b=e<d.length-2?b+(d[e]+"/"):b+d[e]}a.root_path=b;c.filo.ie=!1;c.support.cors=!0;c.filo.maxHeight=90;c.filo.maxWidth=90;
var g=[];c.each(c(".filo"),function(b,a){var d=c(a).attr("id"),e=d+"_"+Date.now()+"_"+Math.round(1E5*Math.random()),e=e.replace(/\./g,"");c(a).attr("id",e);void 0!=c("#"+e).attr("maxCount")&&(g.maxCount=c("#"+e).attr("maxCount"));void 0!=c("#"+e).attr("href")&&(g.href=c("#"+e).attr("href"));void 0!=c("#"+e).attr("newWindow")&&(g.newWindow="true"==c("#"+e).attr("newWindow")?!0:!1);g.method=void 0!=c("#"+e).attr("method")?c("#"+e).attr("method"):"post";t(c,e,d,g);c(window).unbind("resize");c(window).resize(function(){s(c,
g)})})});"undefined"==typeof c.browser&&(c.browser={msie:"Microsoft Internet Explorer"==navigator.appName});Date.now=Date.now||function(){return+new Date}})(jQuery);
